In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.cross_validation import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

D:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data = pd.read_csv("D:\python py\pandas\project\leaf\leaf.csv", names=("Class_Species", "Specimen Number", "Eccentricity","AspectRatio","Elongation","Solidity","StochasticConvexity","Isoperimetric Factor","MaximalIndentation Depth","Lobedness","Average Intensity","Average Contrast","Smoothness","Third moment","Uniformity","Entropy"))
data.head()

Class_Species  Specimen Number  Eccentricity  AspectRatio  Elongation  \
0              1                1       0.72694       1.4742     0.32396   
1              1                2       0.74173       1.5257     0.36116   
2              1                3       0.76722       1.5725     0.38998   
3              1                4       0.73797       1.4597     0.35376   
4              1                5       0.82301       1.7707     0.44462   

   Solidity  StochasticConvexity  Isoperimetric Factor  \
0   0.98535              1.00000               0.83592   
1   0.98152              0.99825               0.79867   
2   0.97755              1.00000               0.80812   
3   0.97566              1.00000               0.81697   
4   0.97698              1.00000               0.75493   

   MaximalIndentation Depth  Lobedness  Average Intensity  Average Contrast  \
0                  0.004657   0.003947           0.047790          0.127950   
1                  0.005242   0.005002           0.024160          0.090476   
2                  0.007457   0.010121           0.011897          0.057445   
3                  0.006877   0.008607           0.015950          0.065491   
4                  0.007428   0.010042           0.007938          0.045339   

   Smoothness  Third moment  Uniformity  Entropy  
0    0.016108      0.005232    0.000275  1.17560  
1    0.008119      0.002708    0.000075  0.69659  
2    0.003289      0.000921    0.000038  0.44348  
3    0.004271      0.001154    0.000066  0.58785  
4    0.002051      0.000560    0.000024  0.34214

In [3]:
data.dtypes

Class_Species                 int64
Specimen Number               int64
Eccentricity                float64
AspectRatio                 float64
Elongation                  float64
Solidity                    float64
StochasticConvexity         float64
Isoperimetric Factor        float64
MaximalIndentation Depth    float64
Lobedness                   float64
Average Intensity           float64
Average Contrast            float64
Smoothness                  float64
Third moment                float64
Uniformity                  float64
Entropy                     float64
dtype: object

In [4]:
data.astype(float).head()

Class_Species  Specimen Number  Eccentricity  AspectRatio  Elongation  \
0            1.0              1.0       0.72694       1.4742     0.32396   
1            1.0              2.0       0.74173       1.5257     0.36116   
2            1.0              3.0       0.76722       1.5725     0.38998   
3            1.0              4.0       0.73797       1.4597     0.35376   
4            1.0              5.0       0.82301       1.7707     0.44462   

   Solidity  StochasticConvexity  Isoperimetric Factor  \
0   0.98535              1.00000               0.83592   
1   0.98152              0.99825               0.79867   
2   0.97755              1.00000               0.80812   
3   0.97566              1.00000               0.81697   
4   0.97698              1.00000               0.75493   

   MaximalIndentation Depth  Lobedness  Average Intensity  Average Contrast  \
0                  0.004657   0.003947           0.047790          0.127950   
1                  0.005242   0.005002           0.024160          0.090476   
2                  0.007457   0.010121           0.011897          0.057445   
3                  0.006877   0.008607           0.015950          0.065491   
4                  0.007428   0.010042           0.007938          0.045339   

   Smoothness  Third moment  Uniformity  Entropy  
0    0.016108      0.005232    0.000275  1.17560  
1    0.008119      0.002708    0.000075  0.69659  
2    0.003289      0.000921    0.000038  0.44348  
3    0.004271      0.001154    0.000066  0.58785  
4    0.002051      0.000560    0.000024  0.34214

In [5]:
X = data.iloc[:,1:]
y = data.iloc[:,0]

In [6]:
X.shape

(340, 15)

In [7]:
y.shape

(340,)

In [8]:
data.shape

(340, 16)

In [9]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=109) # 70% training and 30% test


In [10]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.mean_                                      

array([6.38655462e+00, 7.23500000e-01, 2.54088571e+00, 5.23190168e-01,
       9.02310966e-01, 9.42894244e-01, 5.18311845e-01, 3.69065891e-02,
       4.97573400e-01, 5.16313693e-02, 1.24986353e-01, 1.78067878e-02,
       6.01700004e-03, 3.89351668e-04, 1.16960706e+00])

In [12]:
scaler.scale_

array([3.50536023e+00, 2.13690245e-01, 2.70277352e+00, 1.95268465e-01,
       1.17610857e-01, 1.17043893e-01, 2.16316019e-01, 3.70381174e-02,
       9.54906583e-01, 3.58662039e-02, 5.20521064e-02, 1.37026533e-02,
       5.39673748e-03, 4.47377061e-04, 5.87754051e-01])

In [13]:
scaler.transform(X_train)

array([[-0.68083006, -0.78768219, -0.48434902, ..., -0.05251322,
         0.07071961,  0.32036009],
       [ 0.17500209,  1.00388298,  0.09908869, ..., -0.05180909,
        -0.19422468,  0.07910271],
       [-0.11027529,  0.08853937, -0.36554514, ..., -0.96761239,
        -0.2709832 , -0.49806047],
       ...,
       [ 0.74555686, -0.5785009 , -0.51731516, ...,  0.0320564 ,
        -0.2789854 , -0.02893567],
       [ 0.17500209,  0.90443998,  0.05720579, ...,  0.67803927,
         1.03556568,  1.51235528],
       [ 1.60138902,  0.61308367, -0.17792305, ..., -1.01861357,
        -0.8117597 , -1.43534027]])

In [14]:
X_test_ = X_test
scaler.transform(X_test_)                


array([[-1.25138483,  0.0853104 , -0.37560887, ..., -0.61314823,
        -0.70299909, -0.80478741],
       [-1.53666222, -1.45210185, -0.55590515, ..., -0.02182801,
        -0.44477396,  0.54341257],
       [ 0.74555686,  0.70438405, -0.1722252 , ..., -0.40155743,
        -0.39179851, -0.17066162],
       ...,
       [-0.96610745, -0.81973793, -0.46899443, ..., -0.16923188,
         0.07836417, -0.38015401],
       [ 0.46027948, -0.10459064, -0.38789255, ...,  0.51058625,
         0.3111432 ,  1.03545512],
       [ 1.31611163, -1.46829351, -0.54302949, ...,  0.81567799,
        -0.64100664,  0.01444982]])

In [56]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test_)

In [57]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.08823529411764706


In [55]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, y_pred)

0.3235294117647059

In [18]:
#Import svm model
from sklearn import tree

#Create a svm Classifier
clf = tree.DecisionTreeClassifier() # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test_)

In [19]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.4803921568627451


In [48]:
#Import svm model
from sklearn.ensemble import RandomForestClassifier

    #Create a svm Classifier
clf = RandomForestClassifier(n_estimators=10000, max_depth=5000,
                                 random_state=10) # Linear Kernel

    #Train the model using the training sets
clf.fit(X_train, y_train)

    #Predict the response for test dataset
y_pred = clf.predict(X_test_)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.696078431372549


In [49]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred_ = gnb.fit(X_train,y_train).predict(X_test_)

In [50]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_))

Accuracy: 0.696078431372549


In [51]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, solver='lbfgs',
                         multi_class='multinomial')

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test_)

In [52]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.37254901960784315
